// tests/services/transcript/youtube.test.ts
import { extractPlayerResponse, parseCaptionTracks, parseTimedText, buildTranscript } from '../../../src/services/transcript/youtube'

const MOCK_PLAYER_RESPONSE = {
  captions: {
    playerCaptionsTracklistRenderer: {
      captionTracks: [
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=abc&lang=en',
          name: { simpleText: 'English' },
          languageCode: 'en',
          kind: 'asr',
        },
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=abc&lang=zh-Hans',
          name: { simpleText: 'Chinese (Simplified)' },
          languageCode: 'zh-Hans',
          kind: '',
        },
      ],
    },
  },
}

const MOCK_TIMED_TEXT_XML = `<?xml version="1.0" encoding="utf-8" ?>
<transcript>
  <text start="0.5" dur="2.5">Hello world</text>
  <text start="3.0" dur="2.0">This is a test</text>
  <text start="5.5" dur="1.5">Goodbye</text>
</transcript>`

describe('YouTube transcript', () => {
  describe('extractPlayerResponse', () => {
    it('extracts player response JSON from script tag text', () => {
      const scriptText = `var ytInitialPlayerResponse = ${JSON.stringify(MOCK_PLAYER_RESPONSE)};`
      const result = extractPlayerResponse(scriptText)
      expect(result).not.toBeNull()
      expect(result?.captions).toBeDefined()
    })

    it('returns null when no player response found', () => {
      expect(extractPlayerResponse('var something = 42;')).toBeNull()
    })
  })

  describe('parseCaptionTracks', () => {
    it('extracts caption tracks from player response', () => {
      const tracks = parseCaptionTracks(MOCK_PLAYER_RESPONSE)
      expect(tracks).toHaveLength(2)
      expect(tracks[0].languageCode).toBe('en')
      expect(tracks[0].isAutoGenerated).toBe(true)
      expect(tracks[1].languageCode).toBe('zh-Hans')
      expect(tracks[1].isAutoGenerated).toBe(false)
    })

    it('returns empty array when no captions', () => {
      expect(parseCaptionTracks({})).toEqual([])
    })
  })

  describe('parseTimedText', () => {
    it('parses timed text XML into transcript segments', () => {
      const segments = parseTimedText(MOCK_TIMED_TEXT_XML)
      expect(segments).toHaveLength(3)
      expect(segments[0].text).toBe('Hello world')
      expect(segments[0].startMs).toBe(500)
      expect(segments[0].durationMs).toBe(2500)
    })

    it('handles HTML entities in text', () => {
      const xml = `<transcript><text start="0" dur="1">Hello &amp; world</text></transcript>`
      const segments = parseTimedText(xml)
      expect(segments[0].text).toBe('Hello & world')
    })
  })

  describe('buildTranscript', () => {
    it('joins segments into fullText', () => {
      const transcript = buildTranscript('abc123', 'en', [
        { text: 'Hello world', startMs: 500, durationMs: 2500 },
        { text: 'Goodbye', startMs: 5500, durationMs: 1500 },
      ])
      expect(transcript.videoId).toBe('abc123')
      expect(transcript.platform).toBe('youtube')
      expect(transcript.fullText).toBe('Hello world Goodbye')
    })
  })
})
