import type { Transcript, TranscriptSegment } from '../../shared/types'

export interface CaptionTrack {
  baseUrl: string
  languageCode: string
  name: string
  isAutoGenerated: boolean
}

export function extractPlayerResponse(scriptText: string): Record<string, unknown> | null {
  const marker = 'ytInitialPlayerResponse'
  const idx = scriptText.indexOf(marker)
  if (idx === -1) return null

  const jsonStart = scriptText.indexOf('{', idx)
  if (jsonStart === -1) return null

  let depth = 0
  for (let i = jsonStart; i < scriptText.length; i++) {
    if (scriptText[i] === '{') depth++
    else if (scriptText[i] === '}') {
      depth--
      if (depth === 0) {
        try {
          return JSON.parse(scriptText.slice(jsonStart, i + 1))
        } catch {
          return null
        }
      }
    }
  }
  return null
}

export function parseCaptionTracks(playerResponse: Record<string, unknown>): CaptionTrack[] {
  try {
    const renderer = (playerResponse as {
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: Array<{
            baseUrl: string
            languageCode: string
            name: { simpleText: string }
            kind?: string
          }>
        }
      }
    }).captions?.playerCaptionsTracklistRenderer?.captionTracks

    if (!renderer) return []

    return renderer.map(t => ({
      baseUrl: t.baseUrl,
      languageCode: t.languageCode,
      name: t.name.simpleText,
      isAutoGenerated: t.kind === 'asr',
    }))
  } catch {
    return []
  }
}

export function parseTimedText(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = []
  const regex = /<text start="([\d.]+)"[^>]*dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g
  let match: RegExpExecArray | null

  while ((match = regex.exec(xml)) !== null) {
    const text = match[3]
      .replace(/<[^>]+>/g, '') // strip inner tags before entity decoding
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .trim()

    if (text) {
      segments.push({
        text,
        startMs: Math.round(parseFloat(match[1]) * 1000),
        durationMs: Math.round(parseFloat(match[2]) * 1000),
      })
    }
  }

  return segments
}

export function buildTranscript(videoId: string, language: string, segments: TranscriptSegment[]): Transcript {
  return {
    videoId,
    platform: 'youtube',
    language,
    segments,
    fullText: segments.map(s => s.text).join(' '),
  }
}

export function selectBestTrack(tracks: CaptionTrack[], preferredLang: string): CaptionTrack | null {
  if (tracks.length === 0) return null

  const exactManual = tracks.find(t => t.languageCode === preferredLang && !t.isAutoGenerated)
  if (exactManual) return exactManual

  const exactAuto = tracks.find(t => t.languageCode === preferredLang)
  if (exactAuto) return exactAuto

  const enManual = tracks.find(t => t.languageCode.startsWith('en') && !t.isAutoGenerated)
  if (enManual) return enManual

  const anyManual = tracks.find(t => !t.isAutoGenerated)
  if (anyManual) return anyManual

  return tracks[0]
}

export async function fetchYouTubeTranscript(videoId: string, preferredLang = 'en'): Promise<Transcript | null> {
  const scripts = Array.from(document.scripts)
  let playerResponse: Record<string, unknown> | null = null

  for (const script of scripts) {
    if (!script.src && script.textContent?.includes('ytInitialPlayerResponse')) {
      playerResponse = extractPlayerResponse(script.textContent)
      if (playerResponse) break
    }
  }

  if (!playerResponse) return null

  const tracks = parseCaptionTracks(playerResponse)
  if (tracks.length === 0) return null

  const track = selectBestTrack(tracks, preferredLang)
  if (!track) return null

  const response = await fetch(track.baseUrl)
  if (!response.ok) return null

  const xml = await response.text()
  const segments = parseTimedText(xml)

  return buildTranscript(videoId, track.languageCode, segments)
}
